version: "3.8"

services:
  backend:
    build:
      context: ./oci-alert-backend
    container_name: oci-alert-dashboard-backend
    ports:
      - "5000:5000"
    volumes:
      - "C:/Users/Vaibhav Malhotra/.oci:/root/.oci:ro"
    environment:
      - MONGO_URI=mongodb+srv://vamalhotra751:123@cluster0.pwebx01.mongodb.net/alertDB?retryWrites=true&w=majority&appName=Cluster0
      - ADMIN_USERNAME=himalhotra751@gmail.com
      - ADMIN_PASSWORD=thisner 
      - SQLITE_DB_PATH=./users.sqlite
      - JWT_SECRET=aB7@xYz!pQ3#tUvW2&nM5*oJ8^rT1
      - PORT=5000
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./alert-frontend
    container_name: oci-alert-dashboard-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
